"""Add order relationship to Reviews model

Revision ID: 03235b95b8c0
Revises: 7139379cbc04
Create Date: 2025-12-30 19:55:38.563573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '03235b95b8c0'
down_revision: Union[str, Sequence[str], None] = '7139379cbc04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First, update any NULL Rating values to a default value (e.g., 3)
    op.execute("UPDATE reviews SET \"Rating\" = 3 WHERE \"Rating\" IS NULL")
    
    # Now we can safely set the column to NOT NULL
    op.alter_column('reviews', 'Rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'Rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
