"""add cart tables

Revision ID: 46c2ceb6b311
Revises: ea01ecd3d23c
Create Date: 2026-05-06 21:08:57.075360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46c2ceb6b311'
down_revision: Union[str, Sequence[str], None] = 'ea01ecd3d23c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('user_uid', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('user_uid')
    )
    op.create_table('cart_items',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('cart_uid', sa.Uuid(), nullable=False),
    sa.Column('menu_item_uid', sa.UUID(), nullable=False),
    sa.Column('menu_item_size_uid', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cart_uid'], ['carts.uid'], ),
    sa.ForeignKeyConstraint(['menu_item_size_uid'], ['menu_item_sizes.uid'], ),
    sa.ForeignKeyConstraint(['menu_item_uid'], ['menu_items.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_items')
    op.drop_table('carts')
    # ### end Alembic commands ###
