"""standardize_naming_conventions

Revision ID: 7018414fbf69
Revises: 03235b95b8c0
Create Date: 2025-12-30 22:26:28.402135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7018414fbf69'
down_revision: Union[str, Sequence[str], None] = '03235b95b8c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('quantity', sa.Integer(), nullable=False,server_default='0'))
    op.add_column('orders', sa.Column('order_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False,server_default='pending'))
    op.drop_column('orders', 'Quantity')
    op.drop_column('orders', 'Order_status')
    op.add_column('reviews', sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False,server_default=''))
    op.add_column('reviews', sa.Column('rating', sa.INTEGER(), nullable=False,server_default='0'))
    op.add_column('reviews', sa.Column('order_id', sa.Uuid(), nullable=True))
    op.add_column('reviews', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('reviews_Orders_review_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'orders', ['order_id'], ['uid'])
    op.drop_column('reviews', 'Orders_review')
    op.drop_column('reviews', 'Created_at')
    op.drop_column('reviews', 'Comment')
    op.drop_column('reviews', 'Rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('Rating', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('Comment', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('Created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('Orders_review', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_Orders_review_fkey'), 'reviews', 'orders', ['Orders_review'], ['uid'])
    op.drop_column('reviews', 'created_at')
    op.drop_column('reviews', 'order_id')
    op.drop_column('reviews', 'rating')
    op.drop_column('reviews', 'comment')
    op.add_column('orders', sa.Column('Order_status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('Quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'order_status')
    op.drop_column('orders', 'quantity')
    # ### end Alembic commands ###
