"""added a field in the reviews

Revision ID: 7139379cbc04
Revises: cb81fc585cdc
Create Date: 2025-12-03 23:23:21.870578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7139379cbc04'
down_revision: Union[str, Sequence[str], None] = 'cb81fc585cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('Rating', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'Rating')
    # ### end Alembic commands ###
