"""adde reviews logic

Revision ID: 7a3f1a1f634a
Revises: a35ff6765fb2
Create Date: 2026-04-10 16:08:55.878066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7a3f1a1f634a'
down_revision: Union[str, Sequence[str], None] = 'a35ff6765fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('orders_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'orders', ['orders_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'orders_id')
    # ### end Alembic commands ###
