"""added email verify 

Revision ID: cb81fc585cdc
Revises: ec452a926f3f
Create Date: 2025-12-01 13:42:54.636657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cb81fc585cdc'
down_revision: Union[str, Sequence[str], None] = 'ec452a926f3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'users',
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False)
)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
