"""changed my models 

Revision ID: ec452a926f3f
Revises: 4772126bcaeb
Create Date: 2025-12-01 13:40:04.308843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec452a926f3f'
down_revision: Union[str, Sequence[str], None] = '4772126bcaeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'Order_status',
               existing_type=postgresql.ENUM('PENDING', 'IN_TRANSIT', 'DELIVERED', name='order_status'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('orders', 'pizza_size',
               existing_type=postgresql.ENUM('SMALL', 'MEDUIM', 'LARGE', 'EXTRA_LARGE', name='pizza_size'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.add_column('reviews', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.add_column('reviews', sa.Column('Orders_review', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['uid'])
    op.create_foreign_key(None, 'reviews', 'orders', ['Orders_review'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'Orders_review')
    op.drop_column('reviews', 'user_id')
    op.alter_column('orders', 'pizza_size',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('SMALL', 'MEDUIM', 'LARGE', 'EXTRA_LARGE', name='pizza_size'),
               existing_nullable=False)
    op.alter_column('orders', 'Order_status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('PENDING', 'IN_TRANSIT', 'DELIVERED', name='order_status'),
               existing_nullable=False)
    # ### end Alembic commands ###
